ALTER TABLE users
  ADD COLUMN IF NOT EXISTS push_gmail_review_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS push_insights_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS push_recurring_enabled BOOLEAN NOT NULL DEFAULT TRUE;
